### ISSUE TITLE
Option to use ISO format time in Week Planner

### ISSUE THREAD

**Issue by bolleywall** [abstractspoon/ToDoList_8.3#5]
It would be nice if the Week Planner would show 24h time in stead of AM/PM in the time column when "Display dates and times in ISO format" is ticked in the settings.

**Comment by abstractspoon** [comment]
HI @bolleywall 

Could you possibly transfer this request to thehttps://www.abstractspoon.com/phpBB/viewforum.php?f=7 as I don't typically use Issues to track items?
